config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'welcome#index'
  get 'vision' => 'welcome#vision'
  get 'curriculum' => 'welcome#curriculum'
  get 'team' => 'welcome#team'
  get 'dates' => 'welcome#dates'
  get 'financial' => 'welcome#financial'
  get 'faq' => 'welcome#faq'
  get 'app_faq' => 'welcome#app_faq'
  get 'apply' => 'welcome#apply'
  get 'signup' => 'applicants#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'users/:user_id/apps/:id/edit/:page' => 'apps#edit'
  get 'applicants/:user_id/apps/:id/status' => 'apps#status', as: 'app_status'

  get 'join_our_team' => 'welcome#join_our_team'
  get 'recommender_dashboard' => 'recommenders#index_applicants'
  get 'users/reset-password' => 'users#reset_password_form'
  post 'users/reset-password' => 'users#reset_password'

  get 'admin_panel' => 'welcome#admin_panel'
  post 'create_admin' => 'users#create_admin'
  post 'users/email_all' => 'users#email_all'
  post 'submit' => 'apps#submit'

  get 'applicants/:applicant_id/resume' => 'applicants#show_resume', as: 'resume'
  get 'applicants/:applicant_id/recommendation' => 'applicants#show_recommendation',
        as: 'recommendation'

  resources :users

  resources :applicants do
    resources :apps
  end

  resources :recommenders

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :page

	before_save { self.email = email.downcase }
	validates :first_name, presence: true, length: { maximum: 25 }#, :if => :page_not_three?
	validates :last_name, presence: true, length: { maximum: 25 }#, :if => :page_not_three?
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false}
	has_secure_password#, :if => :page_not_three?
	validates :password, length: { minimum: 6 }, allow_blank: true#, :if => :page_not_three?


	def page_not_three?
		page != '3' && page != "3" && page != 3
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:edit, :update, :show, :index]
	before_action :correct_user, only: [:edit, :update, :show]
	before_action :admin_user, only: [:index, :destroy]

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			#new stuff
			@app = App.create( :first_name => @user.first_name )
			@user.app = @app
			log_in @user
			flash[:success] = "New user successfully created!"
			UserMailer.welcome_email(@user).deliver
			redirect_to root_path
		else
			render 'new'
		end
	end

	def create_admin
		@user = User.new(user_params);
		o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
		random_password = (0...8).map { o[rand(o.length)] }.join
		@user.password = random_password
		@user.password_confirmation = random_password
		@user.admin = true

		if @user.save
			UserMailer.admin_email(@user).deliver
			flash[:success] = "Invitation email sent to recommender"
		else
			flash[:danger] = "Invalid email address"
		end

		redirect_to admin_panel_path
	end

	def email_all
		if params[:user][:applicants].to_i == 1
			@applicants = Applicant.all
			@applicants.each do |applicant|
				UserMailer.all_email(applicant, params[:user][:title],
					params[:user][:message]).deliver
			end
		end
		if params[:user][:administrators].to_i == 1
			@admins = User.where(:admin => true)
			@admins.each do |admin|
				UserMailer.all_email(admin, params[:user][:title],
					params[:user][:message]).deliver
			end
		end
		if params[:user][:recommenders].to_i == 1
			@recommenders = Recommender.all
			@recommenders.each do |recommender|
				UserMailer.all_email(recommender, params[:user][:title],
					params[:user][:message]).deliver
			end
		end
		flash[:success] = "Email sent to all selected parties!"
		redirect_to admin_panel_path
	end

	def show
		@user = User.find(params[:id])
	end

	def index
		@users = User.all
	end

	def destroy
		User.find(params[:id]).destroy
    	flash[:success] = "User deleted"
    	redirect_to users_path
    end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated"
			redirect_to root_path
		else
			render 'edit'
		end
	end

	def reset_password_form
	end

	def reset_password
		#email = params[:email]
		@user = User.find_by({:email => params[:user][:email]})
		if @user != nil
			o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
			random_password = (0...8).map { o[rand(o.length)] }.join
			@user.update_attributes({:password => random_password, :password_confirmation => random_password})
			#@user.password = random_password
			#@user.password_confirmation = random_password

			UserMailer.reset_password_email(@user).deliver
			flash[:success] = "Password reset email sent"
		else
			flash[:danger] = "Invalid email address"
		end

		redirect_to users_reset_password_path
	end

	private
		def user_params
			params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
		end

		def logged_in_user
			unless logged_in?
				store_location
				flash[:danger] = "Please log in."
				redirect_to login_path
			end
		end

		def correct_user
			@user = User.find(params[:id])
			redirect_to root_path unless current_user?(@user)
		end

		def admin_user
			redirect_to(root_path) unless current_user.admin?
		end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Update your profile</h1>

    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :first_name %><br>
        <%= f.text_field :first_name, class: 'form-control' %><br>

        <%= f.label :last_name %><br>
        <%= f.text_field :last_name, class: 'form-control' %><br>

        <%= f.label :email %><br>
        <%= f.text_field :email, class: 'form-control' %><br>

        <%= f.label :password %><br>
        <%= f.password_field :password, class: 'form-control' %><br>

        <%= f.label :password_confirmation, "Confirmation" %><br>
        <%= f.password_field :password_confirmation, class: 'form-control' %><br>

        <%= f.submit "Save changes", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row" id="grad">
    <div class="col-md-8 col-md-offset-2">
        <h1 id="white-text">Listing users</h1>

        <table class="table table-hover table-condensed">
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th></th>
            <th></th>
          </tr>
         
          <% @users.each do |user| %>
            <% if !current_user?(user) %>
              <tr>
                <td><%= user.first_name %> <%= user.last_name %></td>
                <td><%= user.email %></td>
                <td><%= link_to 'View Application', user_app_path(user, user.app), class: 'btn btn-info' %></td>
                <td><%= link_to 'Delete', user, method: :delete, data: { confirm: "Are you sure you want to delete this user?" }, class: 'btn btn-danger' %></td>
              </tr>
            <% end %>
          <% end %>
        </table>
    </div>
</div>

app/views/users/new.html.erb
<div class="row" id="grad">
  <div class="col-md-6 col-md-offset-3">

    <div class="jumbotron">
      <h1>New Applicant</h1><br>

      <%= form_for :user, url: users_path do |f| %>
      <%= render 'shared/error_messages' %>

      <p>
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name, class: 'form-control' %>
      </p>

      <p>
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name, class: 'form-control' %>
      </p>
 
      <p>
        <%= f.label :email %><br>
        <%= f.text_field :email, class: 'form-control' %>
      </p>

      <p>
        <%= f.label :password %><br>
        <%= f.password_field :password, class: 'form-control' %>
      </p>

      <p>
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation, class: 'form-control' %><br>
      </p>
 
      <p>
        <%= f.submit "Create account", class: 'btn btn-primary' %>
      </p>
    <% end %>
    </div>
  </div>
</div>

app/views/users/reset_password_form.html.erb
<% provide(:title, "YMUNI Application") %>

<div class="row" id="grad">
	<div class="col-md-8 col-md-offset-2">
	    <div class="jumbotron">
	        <%= form_for(:user, url: users_reset_password_path, method: :post) do |f| %>
	            <%= hidden_field_tag 'page', params[:page] %>

	            <h1>Reset your password</h1>

	            <%= f.label :email %><br>
	            <%= f.text_field :email, class: 'form-control' %><br>

	            <%= f.submit "Reset password", class: 'btn btn-primary btn-lg' %>
	        <% end %>
	    </div>
	</div>
</div>