config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'welcome#index'
  get 'vision' => 'welcome#vision'
  get 'curriculum' => 'welcome#curriculum'
  get 'team' => 'welcome#team'
  get 'dates' => 'welcome#dates'
  get 'financial' => 'welcome#financial'
  get 'faq' => 'welcome#faq'
  get 'app_faq' => 'welcome#app_faq'
  get 'apply' => 'welcome#apply'
  get 'signup' => 'applicants#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'users/:user_id/apps/:id/edit/:page' => 'apps#edit'
  get 'applicants/:user_id/apps/:id/status' => 'apps#status', as: 'app_status'

  get 'join_our_team' => 'welcome#join_our_team'
  get 'recommender_dashboard' => 'recommenders#index_applicants'
  get 'users/reset-password' => 'users#reset_password_form'
  post 'users/reset-password' => 'users#reset_password'

  get 'admin_panel' => 'welcome#admin_panel'
  post 'create_admin' => 'users#create_admin'
  post 'users/email_all' => 'users#email_all'
  post 'submit' => 'apps#submit'

  get 'applicants/:applicant_id/resume' => 'applicants#show_resume', as: 'resume'
  get 'applicants/:applicant_id/recommendation' => 'applicants#show_recommendation',
        as: 'recommendation'

  resources :users

  resources :applicants do
    resources :apps
  end

  resources :recommenders

end

app/views/shared/_app_error_messages.html.erb
<% if @app.errors.any? %>
  <!--<div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@app.errors.count, "error") %>.
    </div>
    <ul>
    <% @app.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>-->
  <div id="error_explanation" class="alert alert-danger">
      The form contains <%= pluralize(@app.errors.count, "error") %>:
      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <!--<div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>-->
  <div id="error_explanation" class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>:
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!--<div class="navbar-header">
          	<%= link_to "YMUNI", root_path, class: 'navbar-brand' %>
        </div>-->
        <div>
          	<ul class="nav navbar-nav">
                <li id="yale-new-roman"><%= link_to "Home", root_path %></li> <!--, class: 'navbar-brand' -->
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" id="yale-new-roman">About <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li id="yale-new-roman"><%= link_to 'Our Vision', vision_path %></li>
                        <li id="yale-new-roman"><%= link_to 'Our Curriculum', curriculum_path %></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" id="yale-new-roman">YMUNI 2015 <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li id="yale-new-roman"><%= link_to 'Important Dates and Deadlines', dates_path %></li>
                        <li id="yale-new-roman"><%= link_to 'Financial Aid', financial_path %></li>
                        <li id="yale-new-roman"><%= link_to 'FAQ - General', faq_path %></li>
                        <li id="yale-new-roman"><%= link_to 'FAQ - Application', app_faq_path %></li>
                    </ul>
                </li>
                <li id="yale-new-roman"><%= link_to 'Our Team', team_path %></li>
          			<% if logged_in? %>
            				<% if admin? %>
              					<li id="yale-new-roman"><%= link_to 'Manage applicants', applicants_path(sort_param: "id", sort_dir: true) %></li>
              					<li id="yale-new-roman"><%= link_to 'Admin Dashboard', admin_panel_path %></li>
            				<% elsif current_user.type == 'Recommender' %>
                                <li id="yale-new-roman"><%= link_to 'Recommender Dashboard', recommender_dashboard_path %></li>
                            <% else %>
                                <% if current_user.app.submitted? == false %>
                				    <li id="yale-new-roman"><%= link_to 'Application Dashboard', edit_applicant_app_path(current_user, current_user.app) %></li>
                                <% else %>
                                    <li id="yale-new-roman"><%= link_to 'Application Status', app_status_path(current_user, current_user.app) %></li>
                                <% end %>
            				<% end %>
            				<li id="yale-new-roman"><%= link_to "Settings", edit_user_path(current_user) %></li>
                            <!--<li id="yale-new-roman"><%= link_to 'Join Our Team', join_our_team_path %></li>-->
            				<li id="yale-new-roman"><%= link_to 'Log out', logout_path, method: :delete %></li>
        			 <% else %>
                            <!--<li id="yale-new-roman"><%= link_to 'Join Our Team', join_our_team_path %></li>-->
                            <li id="yale-new-roman"><%= link_to 'Apply', apply_path %></li>
        		            <li id="yale-new-roman"><%= link_to 'Login', login_path %></li>
        			 <% end %>
          	</ul>
        </div>
    </div>
</nav>

app/views/shared/_quick_links.html.erb
<div class="col-md-3">
    <h3 id="white-text", class="text-center">Quick links:</h3>
    <%= link_to '(1) General Information', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '1'}), class: 'btn btn-default btn-block' %>
    <%= link_to '(2) Essays', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '2'}), class: 'btn btn-default btn-block' %>
    <%= link_to '(3) Letters of Recommendation', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '3'}), class: 'btn btn-default btn-block' %>
    <%= link_to '(4) Resume', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '4'}), class: 'btn btn-default btn-block' %>
    <%= link_to '(5) GPA and Test Scores', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '5'}), class: 'btn btn-default btn-block' %>
    <%= link_to '(6) Additional Comments', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '6'}), class: 'btn btn-default btn-block' %>
    <%= link_to '(7) Finish', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '7'}), class: 'btn btn-default btn-block' %>
</div>

<!-- <div class="col-md-1"></div> -->

app/views/shared/_recommender_error_messages.html.erb
<% if @recommender.errors.any? %>
  <!--<div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@recommender.errors.count, "error") %>.
    </div>
    <ul>
    <% @recommender.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>-->
  <div id="error_explanation" class="alert alert-danger">
      The form contains <%= pluralize(@recommender.errors.count, "error") %>:
      <ul>
      <% @recommender.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
  </div>
<% end %>