config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'welcome#index'
  get 'vision' => 'welcome#vision'
  get 'curriculum' => 'welcome#curriculum'
  get 'team' => 'welcome#team'
  get 'dates' => 'welcome#dates'
  get 'financial' => 'welcome#financial'
  get 'faq' => 'welcome#faq'
  get 'app_faq' => 'welcome#app_faq'
  get 'apply' => 'welcome#apply'
  get 'signup' => 'applicants#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'users/:user_id/apps/:id/edit/:page' => 'apps#edit'
  get 'applicants/:user_id/apps/:id/status' => 'apps#status', as: 'app_status'

  get 'join_our_team' => 'welcome#join_our_team'
  get 'recommender_dashboard' => 'recommenders#index_applicants'
  get 'users/reset-password' => 'users#reset_password_form'
  post 'users/reset-password' => 'users#reset_password'

  get 'admin_panel' => 'welcome#admin_panel'
  post 'create_admin' => 'users#create_admin'
  post 'users/email_all' => 'users#email_all'
  post 'submit' => 'apps#submit'

  get 'applicants/:applicant_id/resume' => 'applicants#show_resume', as: 'resume'
  get 'applicants/:applicant_id/recommendation' => 'applicants#show_recommendation',
        as: 'recommendation'

  resources :users

  resources :applicants do
    resources :apps
  end

  resources :recommenders

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :logged_in_user, only: [:admin_panel]
	before_action :admin_user, only: [:admin_panel]

	def about
	end

	def vision
	end

	def curriculum
	end

	def team
	end

	def dates
	end

	def financial
	end

	def faq
	end

	def app_faq
	end

	def apply
	end

	def join_our_team
	end

	def admin_panel
		@users = User.where(:admin => true)
	end

	private
		def admin_user
			redirect_to(root_path) unless current_user.admin?
		end

		def logged_in_user
			unless logged_in?
				store_location
				flash[:danger] = "Please log in."
				redirect_to login_path
			end
		end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<h1>About us</h1>

<p>Jason Gaitonde is the Supreme Ruler of YMUNI. Bow before him.</p><br>
<%= image_tag('1620428_944244342268429_4509758216877041993_n.jpg') %><br>

app/views/welcome/admin_panel.html.erb
<% provide(:title, "YMUNI Application") %>

<div class="row" id="grad">
    <div class="col-md-8 col-md-offset-1">
        <h1 id="white-text">Admin Dashboard</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-5 col-md-offset-1">
        <h1 id="white-text">Invite an Administrator</h1>

        <div class="jumbotron">
            <%= form_for(:user, url: create_admin_path) do |f| %>
                
                <%= f.label :first_name %><br>
                <%= f.text_field :first_name, class: 'form-control' %><br>

                <%= f.label :last_name %><br>
                <%= f.text_field :last_name, class: 'form-control' %><br>

                <%= f.label :email %><br>
                <%= f.text_field :email, class: 'form-control' %><br>

                <%= f.submit "Invite admin", class: 'btn btn-primary btn-lg' %>
            <% end %>
        </div>
    </div>

    <div class="col-md-4 col-md-offset-1">
        <h1 id="white-text">Listing Administrators</h1>

        <table class="table table-hover table-condensed">
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th></th>
            <th></th>
          </tr>
         
          <% @users.each do |user| %>
              <tr>
                <td><%= user.first_name %> <%= user.last_name %></td>
                <td><%= user.email %></td>
              </tr>
          <% end %>
        </table>
    </div>
</div>

<div class="row">
    <div class="col-md-5 col-md-offset-1">
        <h1 id="white-text">Send an email to all:</h1>

        <div class="jumbotron">
            <%= form_for(:user, url: users_email_all_path, method: :post) do |f| %>
                <%= f.label :applicants, class: 'checkbox' do %>
                    <%= f.check_box :applicants %>
                    Applicants
                <% end %>

                <%= f.label :administrators, class: 'checkbox' do %>
                    <%= f.check_box :administrators %>
                    Administrators
                <% end %>

                <%= f.label :recommenders, class: 'checkbox' do %>
                    <%= f.check_box :recommenders %>
                    Recommenders
                <% end %>

                <br>
                <%= f.label :title %><br>
                <%= f.text_field :title, class: 'form-control' %><br>
                
                <%= f.label :message %><br>
                <%= f.text_area :message, class: 'form-control', :size => "30x10" %><br>

                <%= f.submit "Send emails", class: 'btn btn-primary btn-lg' %>
            <% end %>
        </div>
    </div>
</div>

app/views/welcome/app_faq.html.erb
<div class="row" id="grad">
  	<div class="col-md-10 col-md-offset-1">
	    <!--<h1 class="text-center">Our Vision</h1><br>-->
		
		<div class="jumbotron">
			<h1 class="text-center">Frequently asked application questions</h1><br>

			<h2>How do I submit the application?</h2>
			<p>Originally, this was to be done automatically on the day of the deadline. Now, there is a "submit" button at the end of the application.</p>

			<h2>What do I do if I want to enter a test score other than the ones listed in Part 5?</h2>
			<p>Please list it in the "Additional Comments" section. Additionally, if you do not have a score for one of the listed tests, simply enter nothing in the field. The same goes for the GPA field.</p>

			<h2>The application does not allow me to enter my GPA.</h2>
			<p>You must enter a GPA of 4.0 or below, as we are evaluating unweighted GPA. If you truly feel inclined to list your weighted GPA, please do so in the "Additional Comments" section.</p>

			<h1 class="text-center">Other important application notes</h1><br>

			<h2>Click the "Save changes" button!</h2>
			<p>This must be done before navigating to another page in order to save your changes successfully.</p>

			<h2>Other Questions or Concerns?</h2>
			<p>Please email <%= mail_to "tech.ymuni@yira.org" %> regarding an application-specific questions.</p><br>
			
			<p>Finally, thank you all for your patience as we work the bugs out of our site! We sincerely look forward to reading your applications.</p>
		</div>
  	</div>
</div>

app/views/welcome/apply.html.erb
<div class="row" id="grad">
  	<div class="col-md-10 col-md-offset-1">
	    <!--<h1 class="text-center">Our Vision</h1><br>-->

		<div class="jumbotron">
			<h1 class="text-center">Application Instructions</h1><br>

			<p>Admission to YMUNI 2015 requires submission of an online application. As of July 9, 2015: We are currently accepting applications to fill remaining spots in our program. Applications are being reviewed on a first-come, first-serve basis. Please complete your online application and email <%= mail_to "ymuni@yira.org" %> about the status of your application.</p>

			<p>The application is composed of four parts: Basic Information, Essays, 1 Letter of Recommendation, and Scores. YMUNI maintains a holistic approach to admissions. We want to know who you are, where you come from, and what you will be able to contribute to the YMUNI community.</p>

			<p>High school students who will be entering the 10th-12th grades (between the ages of 14-17) the fall of 2015 are eligible to apply. The application is open to domestic and international students.</p>

			<p>YMUNI is looking for students who are passionate about learning about the world around them and who are eager to seek their highest potential as students, scholars, and leaders.</p>

			<p>We look forward to reading your application!</p>

			<p>Questions? Email <%= mail_to "ymuni@yira.org" %>.</p>

			<br>

			<ol>
				<h2><li>Create a YMUNI 2015 account <%= link_to "here", signup_path %></li></h2>
				<h2><li>By creating an account, you will be able to save and return to your application.</li></h2>
				<h2><li>All applications will be submitted online.</li></h2>
				<h2><li>Once you have submitted your application, your online status should come up as “Completed.” You will also receive a confirmation email once your application has been received.</li></h2>
			</ol>

			<br>
			*Admission or rejection to YMUNI is by no means a reflection of admissions to Yale College. YMUNI operates as a constituent program of the Yale International Relations Association (YIRA), a registered student organization and 501(c) 3 non-profit.
		</div>
  	</div>
</div>

app/views/welcome/curriculum.html.erb
<div class="row" id="grad">
  	<div class="col-md-10 col-md-offset-1">
	    <!--<h1 class="text-center">Our Vision</h1><br>-->
		
		<div class="jumbotron">
			<h1 class="text-center">Our Curriculum</h1><br>

			<h2 class="text-center">International Relations</h2>
			<h2 class="text-center">Model United Nations committee sessions</h2>
			<h2 class="text-center">College panels</h2>
			<h2 class="text-center">Trip to the United Nations</h2>
			<h2 class="text-center">Interaction with Yale Professors and Resources</h2>
			<h2 class="text-center">Tour of Yale</h2><br><br>
			<p>At YMUNI, students will learn about three main things: international relations, leadership, and Model UN. Students will engage with renowned Yale professors lecture on IR theory and with Yale students through discussions about topics in international development and security, from ISIS to climate change to globalization. Participants will also work with Yale students to develop and refine public speaking, argumentative writing, and research skills, as well as learn about and discuss ways to improve self-image and confidence within and beyond MUN. In addition, students will participate in two mock MUN committees, where they will practice their skills and ideas and receive individualized feedback. Participants will also get to explore Yale and New Haven through various activities and tours, learn about applying to college, visit the UN in New York City, and socialize with similar students from across the country. All classes, committee sessions, workshops, and social events will be planned and led by Yale students, the YMUNI team, for the enjoyment and education of the participants.</p>
		</div>
  	</div>
</div>

app/views/welcome/dates.html.erb
<div class="row" id="grad">
  	<div class="col-md-10 col-md-offset-1">
	    <!--<h1 class="text-center">Our Vision</h1><br>-->
		
		<div class="jumbotron">
			<h1 class="text-center">Important Dates and Deadlines</h1><br>

			<div class="row">
				<div class="col-md-3 col-md-offset-1">
					<!--<h2>January 21:</h2>
					<h2>March 29:</h2>
					<h2>TBA:</h2>
					<h2>May 1:</h2>-->
					<h2>August 2-8:</h2>
				</div>

				<div class="col-md-8">
					<!--<h2>Application opens</h2>
					<h2>Application deadline</h2>
					<h2>Admissions decisions released</h2>
					<h2>Confirmation of participation in YMUNI 2015</h2>-->
					<h2>YMUNI 2015!</h2>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-10 col-md-offset-1">
					<h2>Applications are still being accepted! Apply today</h2>
				</div>
			</div>
		</div>
  	</div>
</div>

app/views/welcome/faq.html.erb
<div class="row" id="grad">
  	<div class="col-md-10 col-md-offset-1">
	    <!--<h1 class="text-center">Our Vision</h1><br>-->
		
		<div class="jumbotron">
			<h1 class="text-center">Frequently asked questions</h1><br>

			<h2>How much will it cost to attend the program?</h2>
			<p>The cost of the program will be $1500. All program participants will be living on Yale’s campus in one of the residential colleges for the entirety of the program. Program tuition will cover housing, meals, program expenses and materials, and a trip to New York during the program. More information about paying for the program will be released once students are admitted.</p>

			<h2>Is there an application fee?</h2>
			<p>No, there is no fee to apply to YMUNI.</p>

			<h2>Is there financial aid available?</h2>
			<p>Yes. YMUNI  all applicants are invited to apply for financial aid. More information can be found <%= link_to 'here', financial_path %>.</p>

			<h2>Who is eligible to apply?</h2>
			<p>High school students, domestically and internationally, are eligible to apply for YMUNI. High school students who will be entering the 10th-12th grades (between the ages of 14-17) the fall of 2015 are eligible to apply.</p>

			<h2>Is MUN experienced required?</h2>
			<p>MUN experience is not required for admission to the program. However, if you do have Model UN experience, please do elaborate where applicable in the online application.</p>
			
			<p>If you do not have Model UN experience, please write about why you want to learn more about MUN through YMUNI. You may also talk about similar extracurriculars activities to MUN.</p>
		</div>
  	</div>
</div>

app/views/welcome/financial.html.erb
<div class="row" id="grad">
  	<div class="col-md-10 col-md-offset-1">
	    <!--<h1 class="text-center">Our Vision</h1><br>-->
		
		<div class="jumbotron">
			<h1 class="text-center">Financial Aid</h1><br>
			<p>Financial Aid: Partial financial aid offered on a case by case basis. Please follow the financial aid application, and be sure to submit any supplemental information in the text box to explain your financial situation. At YMUNI we strive to provide access to our program for all of the students who are accepted, and urge students to seek out external scholarships after they receive their admissions decision.</p>
		</div>
  	</div>
</div>

app/views/welcome/index.html.erb
<div class="row" id="grad">
  	<div class="col-md-10 col-md-offset-1">
	    <!--<h1 class="text-center", id="white-text">Welcome to Yale Model United Nations Institute</h1><br>-->
		<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
	  	<!-- Indicators -->
	  		<ol class="carousel-indicators">
		    	<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
		    	<li data-target="#carousel-example-generic" data-slide-to="1"></li>
		    	<li data-target="#carousel-example-generic" data-slide-to="2"></li>
	  		</ol>

	  	<!-- Wrapper for slides -->
	  	<div class="carousel-inner" role="listbox">
	    	<div class="item active">
	      		<%= image_tag 'YMUNISITEPHOTO1.jpg', class: 'tales' %>
	      	<div class="carousel-caption">
	    	</div>
	    	</div>
	    	<div class="item">
	      		<%= image_tag 'yale17.jpg', class: 'tales' %>
	      	<div class="carousel-caption">
	      	</div>
	    	</div>
	    	<div class="item">
	      		<%= image_tag 'YMUNISITEPHOTO2.jpg', class: 'tales' %>
	      	<div class="carousel-caption">
	      	</div>
	    	</div>
	  	</div>

	  	<!-- Controls -->
	  	<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
	    	<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	    	<span class="sr-only">Previous</span>
	  	</a>
	  	<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
	    	<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	    	<span class="sr-only">Next</span>
	  	</a>
		</div><br>


		<div class="jumbotron">
			<h1 class="text-center">Letter from the Executive Director</h1><br><br>

			<div class="row" id="grad">
  				<div class="col-md-10 col-md-offset-1">
					<p>It is with deep pleasure that I welcome you to the official website of YMUNI 2015. The Yale Model United Nations Institute is the newest constituent program of the Yale International Relations Association (YIRA). The Yale International Relations Association is known for running some of the world’s best high school Model United Nations conferences -- from New Haven, to China, to Taipei, to Seoul, and to Budapest. Over the course of our history, we have educated thousands of students from around the world, and we continually seek to expand our educational impact. We now introduce to you the Yale Model United Nations Institute (YMUNI 2015).</p>

					<p>YMUNI serves as YIRA’s premiere summer program about international relations, leadership and Model United Nations right here at Yale in beautiful New Haven, Connecticut. The program is entirely designed and run by Yale students themselves, who are all deeply committed to the world, education, and the power of Model United Nations.</p>

					<p>We invite you to join YMUNI 2015 to learn more about the world, to experience Yale, to polish your MUN and debate skills. But most of all, we invite you to join YMUNI 2015 to challenge yourself to become the best student, scholar and leader you can possibly be.</p>

					<p>Welcome to the Yale Model United Nations Institute, YIRA’s newest program. We’ll see you in New Haven.</p>

					<p>Sincerely,</p>
					<p>Hannah Gonzales<br>
					Executive Director, YMUNI 2015</p>
				</div>
			</div>
		</div>
  	</div>
</div>

app/views/welcome/join_our_team.html.erb
<div class="row" id="grad">
  	<div class="col-md-10 col-md-offset-1">
	    <!--<h1 class="text-center">Our Vision</h1><br>-->
		
		<div class="jumbotron">
			<h1 class="text-center">Teach for YMUNI!</h1><br>

			<p>Teach for YIRA’s newest constituent program! Make an impact on the lives of thirty high school students from around the world by joining the YMUNI Team. The Yale Model United Nations Institute (YMUNI) is currently looking for Teachers for its program this August 2-8, 2015. YMUNI Teachers will mentor program participants, share their passion for Yale, international relations and Model United Nations, and design and execute program curriculum.</p>

			<p class="thick-italic">The YMUNI Teacher position is a paid position. Housing and meals are all covered, and teachers will receive a $300 stipend upon completion of the program.</p>
			<p class="thick">The application can be found <%= link_to "here", "https://docs.google.com/forms/d/1h7rOQ0oy9F0nXfknn_56V300qUqyd-CqAJrBjQ3pDt8/viewform" %>.</p>

			<p class="thick-italic">Applications are due by this Friday, February 20.</p><br>
			
			<h2 class="thick">OPEN POSITIONS</h2>
			<h2 class="thick">1) Director of Conference and Delegate Affairs</h2>
			<p>The YMUNI Director of Delegate Affairs, who must be over the age of 21, will be responsible for delegate conduct and supervision. The Director of Delegate Affairs will create and review program policies and procedures. The Director should have previous teaching and MUN experience, and background in conference organizing would be highly preferred. Previous experience building a YIRA constituent program is a plus. The Director of Conference and Delegate Affairs will receive a $500 stipend upon completion of the program.</p>

			<h2 class="thick">2) Director of Curriculum</h2>
			<p>The YMUNI Director of Curriculum and Delegate Activities will oversee the educational aspect of YMUNI and will be responsible for developing program curriculum. The program is currently slated to have workshops, guest lectures, and practice committee sessions, but the Director will also have the opportunity to introduce new and useful delegate activities to enhance the YMUNI vision. The Director will also help define the educational atmosphere of YMUNI. Prior teaching experience (in and out of the context of MUN), as well as MUN experience is highly preferred. The Director of Curriculum and Delegate Activities will organize and run Instructor trainings in the Spring semester. A passion for teaching and a commitment to education are vital for this position. The Director of Curriculum and Delegate Activities will have the opportunity to help expand YIRA’s educational impact. The Director of Curriculum will receive a $500 stipend upon completion of the program.</p><br>
			
			<p>If you are interested in applying for these positions, send an email expressing your interest to Executive Director Hannah Gonzales at <%= mail_to "ymuni@yira.org" %>.</p>
		</div>
  	</div>
</div>

app/views/welcome/team.html.erb
<div class="row" id="grad">
  	<div class="col-md-10 col-md-offset-1">
	    <div class="jumbotron">
			<h1 class="text-center">Meet our team</h1><br>

			<h3>Executive Director, Hannah Gonzales</h3>
		    <div class="row">
		    	<div class="col-md-6">
		    		<%= image_tag 'hannah.jpg' %>
		    	</div>

		    	<div class="col-md-6">
		    		<p>Hannah Gonzales is a junior in Calhoun College majoring in History. Hannah began her Model United Nations career in high school and has pursued it ever since. Hannah is a member of the Model United Nations Team at Yale, chairs for YIRA’s conferences at home and abroad, and most of all, enjoys teaching high school students about the world and Model United Nations. She also had the opportunity work for Best Delegate as a Summer Programs Counselor during the summer of 2013. Hannah is both excited and honored to be leading YMUNI 2015. She looks forward to sharing her vision with others and to building a community based on the educational values of Model United Nations.</p>
		    	</div>
		    </div>

		    <h3>Director of Culture, Jake Colavolpe</h3>
		    <div class="row">
		    	<div class="col-md-6">
		    		<%= image_tag 'IMG_7522.jpg' %>
		    	</div>

		    	<div class="col-md-6">
		    		<p>Jake Colavolpe is a freshman in Morse College intending to double major in WGSS and Sociology. Jake began his involvement with MUN in high school, through YIRA’s Hemipheres program. He loves teaching, being both an instructor for Hemispheres and the head debate coach for Wilbur Cross High School in New Haven. Jake is thrilled to be the Director of Culture of this year’s YMUNI. He looks forward to helping to reshape MUN life and cutlure through YMUNI 2015!</p>
		    	</div>
		    </div>

		    <h3>KJ Ong, Director of Conference & Delegate Affairs</h3>
		    <div class="row">
		    	<div class="col-md-6">
		    		<%= image_tag 'IMG_7513.jpg' %>
		    	</div>

		    	<div class="col-md-6">
		    		<p>KJ Ong is a Malaysian sophomore in Berkeley College majoring in History. His academic interests are democracy movements against authoritarian states, ethnic conflict & genocide, and digital humanities. Prior to coming to Yale, KJ took a gap year in his home country, working for a think tank, a political party, a human rights lawyers organization, and a coalition of democracy activists. At Yale, KJ was the Director General of Committees for Yale Model United Nations XLI, the Community Secretary of the Liberal Party of the Yale Political Union, and the Outreach Director of the Yale Gamers Club. He is deeply passionate about connecting real world issues to everyday classroom experiences, and is extremely excited to see all of you at YMUNI! </p>
		    	</div>
		    </div>

		    <h3>Miranda Melcher, Director of Curriculum</h3>
		    <div class="row">
		    	<div class="col-md-6">
		    		<%= image_tag 'IMG_7518.jpg' %>
		    	</div>

		    	<div class="col-md-6">
		    		<p>Miranda Melcher is a rising senior in Branford College at Yale University and is this year’s Director of Curriculum for YMUNI. Miranda is a political science major, studying on civil wars in the Middle East and Africa. Miranda grew up as an expat in Beijing, China, where she attended international school and many MUN conferences. Outside of YMUNI, Miranda is involved with YMUN, YMUN Korea, Hemispheres, Jewish life at Yale, and a member of the Yale Political Union. Miranda sees YMUNI as a great opportunity to work with exceptional high school students and way to give back her years of IR and MUN knowledge. Please do not hesitate to reach out to Miranda with any questions at teach.ymuni@yira.org.</p>
		    	</div>
		    </div>
		</div>
  	</div>
</div>

app/views/welcome/vision.html.erb
<div class="row" id="grad">
  	<div class="col-md-10 col-md-offset-1">
	    <!--<h1 class="text-center">Our Vision</h1><br>-->
		
		<div class="jumbotron">
			<h1 class="text-center">Our Vision</h1>

			<p>The Yale Model United Nations Institute, or YMUNI, is a one-week long residential summer program for high school students about leadership, international relations, and Model United Nations run by Yale students from the Yale International Relations Association. Through YMUNI, program participants will learn more about the world, themselves, YIRA, and the amazing resources Yale has to offer.</p>

			<p>YMUNI participants will leave the program with:</p> 

			<p>
				<ul>
					<li>a better understanding of international relations and global affairs</li>
					<li>refined MUN skills, such as public speaking, research, writing and debate</li>
					<li>the experience of living in one of Yale’s residential colleges</li>
					<li>new friendships</li>
					<li>exposure to Yale professors and resources</li>
					<li>the opportunity to learn and to connect with some of Yale’s best and brightest students</li>
				</ul>
			</p>

			<p>YMUNI 2015 will be held at Yale University from August 2-8, 2015.</p>

			<p>YMUNI is operated as a constituent program of the Yale International Relations Association (YIRA). 
				YIRA is one of Yale’s largest student organizations, with 501c3 non-profit status. More information about YIRA can be found <%= link_to "here", "http://www.yira.org" %></p>

			<p>Apply today and join us for what will be an incredible week at Yale, YMUNI 2015.</p>
		</div>
  	</div>
</div>