config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'welcome#index'
  get 'vision' => 'welcome#vision'
  get 'curriculum' => 'welcome#curriculum'
  get 'team' => 'welcome#team'
  get 'dates' => 'welcome#dates'
  get 'financial' => 'welcome#financial'
  get 'faq' => 'welcome#faq'
  get 'app_faq' => 'welcome#app_faq'
  get 'apply' => 'welcome#apply'
  get 'signup' => 'applicants#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'users/:user_id/apps/:id/edit/:page' => 'apps#edit'
  get 'applicants/:user_id/apps/:id/status' => 'apps#status', as: 'app_status'

  get 'join_our_team' => 'welcome#join_our_team'
  get 'recommender_dashboard' => 'recommenders#index_applicants'
  get 'users/reset-password' => 'users#reset_password_form'
  post 'users/reset-password' => 'users#reset_password'

  get 'admin_panel' => 'welcome#admin_panel'
  post 'create_admin' => 'users#create_admin'
  post 'users/email_all' => 'users#email_all'
  post 'submit' => 'apps#submit'

  get 'applicants/:applicant_id/resume' => 'applicants#show_resume', as: 'resume'
  get 'applicants/:applicant_id/recommendation' => 'applicants#show_recommendation',
        as: 'recommendation'

  resources :users

  resources :applicants do
    resources :apps
  end

  resources :recommenders

end

app/views/apps/edit-2.html.erb
<% provide(:title, "YMUNI Application") %>

<div class="row" id="grad">
    <%= render 'shared/quick_links' %>

    <div class="col-md-6" > <!--col-md-offset-3">-->
        <h1 id="white-text">YMUNI Application</h1>
        <h2 id="white-text">Part 2 - Essays</h2><br>

        <div class="jumbotron">
            <%= form_for([@user, @app]) do |f| %>
                <%= hidden_field_tag 'page', params[:page] %>
                <%= render 'shared/app_error_messages' %>

                <%= f.label :personal_statement %> (500-750 words)<br>
                <%= f.text_area :personal_statement, class: 'form-control', :size => "30x10" %><br>

                <p class="thick", id="normal-text-size">Please limit answers to supplemental questions to 250-500 words</p>

                <%= f.label :supplemental_question_1 %><br> 
                <p id="normal-text-size">Why do you want to participate in YMUNI 2015?</p>
                <%= f.text_area :supplemental_question_1, class: 'form-control', :size => "30x10" %><br>

                <%= f.label :supplemental_question_2 %><br>
                <p id="normal-text-size">Please talk about your previous MUN experience. If you have no previous MUN experience, please talk about another similar activity.</p>
                <%= f.text_area :supplemental_question_2, class: 'form-control', :size => "30x10" %><br>

                <%= f.label :supplemental_question_3 %><br>
                <p id="normal-text-size">Tell us about a leadership experience that has been important to your development.</p>
                <%= f.text_area :supplemental_question_3, class: 'form-control', :size => "30x10" %><br>

                <%= f.label :supplemental_question_4 %><br>
                <p id="normal-text-size">Tell us about the community you come from and how that has impacted your worldview.</p>
                <%= f.text_area :supplemental_question_4, class: 'form-control', :size => "30x10" %><br>

                <%= f.label :supplemental_question_5 %><br>
                <p id="normal-text-size">What do you like to do during your free time?</p>
                <%= f.text_area :supplemental_question_5, class: 'form-control', :size => "30x10" %><br>
               
                <%= f.submit "Save changes", class: 'btn btn-primary' %>
            <% end %>
        </div>
        <nav>
          <ul class="pagination pagination-lg pagination-centered">
            <li><%= link_to '<<', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '1'}) %></li>
            <li><%= link_to '1', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '1'}) %></li>
            <li class="active"><%= link_to '2', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '2'}) %></li>
            <li><%= link_to '3', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '3'}) %></li>
            <li><%= link_to '4', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '4'}) %></li>
            <li><%= link_to '5', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '5'}) %></li>
            <li><%= link_to '6', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '6'}) %></li>
            <li><%= link_to '7', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '7'}) %></li>
            <li><%= link_to '>>', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '3'}) %></li>
          </ul>
        </nav>
    </div>
</div>

app/views/apps/edit-3.html.erb
<% provide(:title, "YMUNI Application") %>

<div class="row" id="grad">
    <%= render 'shared/quick_links' %>

    <div class="col-md-6" > <!--col-md-offset-3">-->
        <h1 id="white-text">YMUNI Application</h1>
        <h2 id="white-text">Part 3 - Letters of Recommendation</h2><br>

        <div class="jumbotron">
            <%= form_for(:recommender, url: recommenders_path) do |f| %>
                <%= hidden_field_tag 'page', params[:page] %>
                <%= render 'shared/error_messages' %>
                <%= render 'shared/recommender_error_messages' %>
                
                <% if @recommender.first_name == nil %>
                    <h1>Invite a recommender!</h1>
                    <p>Recommendations should be one-page in length, detailing the student’s achievements, strengths and qualities. 
                    Recommendations should come from secondary school teachers. Please invite only one recommender.</p><br>
                <% else %>
                    <h2><%= @recommender.first_name %> has been successfully invited.</h2>
                    <p>Only resubmit the form below if you wish to change your recommender. If so, please communicate with your previous recommender to let them know of this change as they will become locked out of the system.</p>
                <% end %>

                <%= f.label :recommender_first_name %><br>
                <%= f.text_field :first_name, class: 'form-control' %><br>

                <%= f.label :recommender_last_name %><br>
                <%= f.text_field :last_name, class: 'form-control' %><br>

                <%= f.label :email %><br>
                <%= f.text_field :email, class: 'form-control' %><br>

                <%= f.submit "Invite recommender", class: 'btn btn-primary btn-lg' %>
            <% end %>
        </div>

    <nav>
      <ul class="pagination pagination-lg pagination-centered">
        <li><%= link_to '<<', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '2'}) %></li>
        <li><%= link_to '1', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '1'}) %></li>
        <li><%= link_to '2', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '2'}) %></li>
        <li class="active"><%= link_to '3', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '3'}) %></li>
        <li><%= link_to '4', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '4'}) %></li>
        <li><%= link_to '5', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '5'}) %></li>
        <li><%= link_to '6', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '6'}) %></li>
        <li><%= link_to '7', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '7'}) %></li>
        <li><%= link_to '>>', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '4'}) %></li>
      </ul>
    </nav>
  </div>
</div>

app/views/apps/edit-4.html.erb
<% provide(:title, "YMUNI Application") %>

<div class="row" id="grad">
    <%= render 'shared/quick_links' %>

    <div class="col-md-6" > <!--col-md-offset-3">-->
        <h1 id="white-text">YMUNI Application</h1>
        <h2 id="white-text">Part 4 - Resume</h2><br>

        <div class="jumbotron">
            <%= form_for(@user) do |f| %>
                <%= hidden_field_tag 'page', params[:page] %>
                <%= render 'shared/app_error_messages' %>
                <h2>Upload your resume</h2><br>

                <!-- <p>
                    <% if @user.resume.path != nil %>
                        Uploaded file: <%= File.basename(@user.resume.path) %><br><br>
                    <% end %>
                    <%= f.file_field :resume %>
                    <%= f.hidden_field :resume_cache %>
                </p> -->
                <p>
                    <% if File.exists?("#{@user.resume.path}") %>
                        Uploaded file: <%= File.basename(@user.resume.path) %><br><br>
                    <% end %>
                    <%= f.file_field :resume %>
                    <%= f.hidden_field :resume_cache %>
                </p>
            
                <%= f.submit "Upload", class: 'btn btn-primary' %>
            <% end %>
        </div> 

    <nav>
      <ul class="pagination pagination-lg pagination-centered">
        <li><%= link_to '<<', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '3'}) %></li>
        <li><%= link_to '1', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '1'}) %></li>
        <li><%= link_to '2', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '2'}) %></li>
        <li><%= link_to '3', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '3'}) %></li>
        <li class="active"><%= link_to '4', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '4'}) %></li>
        <li><%= link_to '5', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '5'}) %></li>
        <li><%= link_to '6', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '6'}) %></li>
        <li><%= link_to '7', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '7'}) %></li>
        <li><%= link_to '>>', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '5'}) %></li>
      </ul>
    </nav>
  </div>
</div>

app/views/apps/edit-5.html.erb
<% provide(:title, "YMUNI Application") %>

<div class="row" id="grad">
    <%= render 'shared/quick_links' %>

    <div class="col-md-6" > <!--col-md-offset-3">-->
        <h1 id="white-text">YMUNI Application</h1>
        <h2 id="white-text">Part 5 - GPA and Scores</h2><br>

        <div class="jumbotron">
            <%= form_for([@user, @app]) do |f| %>
                <%= hidden_field_tag 'page', params[:page] %>
                <%= render 'shared/app_error_messages' %>

                <%= f.label :gpa %><br>
                <%= f.number_field :gpa, class: 'form-control' %><br>

                <%= f.label :sat_score %><br>
                <%= f.number_field :sat_score, class: 'form-control' %><br>

                <%= f.label :act_score %><br>
                <%= f.number_field :act_score, class: 'form-control' %><br>

                <%= f.label :toefl_score %><br>
                <%= f.number_field :toefl_score, class: 'form-control' %><br>

                <%= f.submit "Save changes", class: 'btn btn-primary' %>
            <% end %>
        </div>

    <nav>
      <ul class="pagination pagination-lg pagination-centered">
        <li><%= link_to '<<', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '4'}) %></li>
        <li><%= link_to '1', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '1'}) %></li>
        <li><%= link_to '2', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '2'}) %></li>
        <li><%= link_to '3', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '3'}) %></li>
        <li><%= link_to '4', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '4'}) %></li>
        <li class="active"><%= link_to '5', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '5'}) %></li>
        <li><%= link_to '6', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '6'}) %></li>
        <li><%= link_to '7', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '7'}) %></li>
        <li><%= link_to '>>', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '6'}) %></li>
      </ul>
    </nav>
  </div>
</div>

app/views/apps/edit-6.html.erb
<% provide(:title, "YMUNI Application") %>

<div class="row" id="grad">
    <%= render 'shared/quick_links' %>

    <div class="col-md-6" > <!--col-md-offset-3">-->
        <h1 id="white-text">YMUNI Application</h1>
        <h2 id="white-text">Part 6 - Additional Comments?</h2><br>

        <div class="jumbotron">
            <%= form_for([@user, @app]) do |f| %>
                <%= hidden_field_tag 'page', params[:page] %>
                <%= render 'shared/app_error_messages' %>

                <p id="normal-text-size">Any additional comments? (Completely optional, 250-500 words)</p>
                <%= f.text_area :additional_comments, class: 'form-control', :size => "30x10" %><br>

                <%= f.submit "Save changes", class: 'btn btn-primary' %>
            <% end %>
        </div>
        <nav>
          <ul class="pagination pagination-lg pagination-centered">
            <li><%= link_to '<<', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '1'}) %></li>
            <li><%= link_to '1', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '1'}) %></li>
            <li><%= link_to '2', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '2'}) %></li>
            <li><%= link_to '3', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '3'}) %></li>
            <li><%= link_to '4', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '4'}) %></li>
            <li><%= link_to '5', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '5'}) %></li>
            <li class="active"><%= link_to '6', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '6'}) %></li>
            <li><%= link_to '7', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '7'}) %></li>
            <li><%= link_to '>>', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '7'}) %></li>
          </ul>
        </nav>
    </div>
</div>

app/views/apps/edit-7.html.erb
<% provide(:title, "YMUNI Application") %>

<div class="row" id="grad">
    <%= render 'shared/quick_links' %>

    <div class="col-md-6" > <!--col-md-offset-3">-->
        <h1 id="white-text">YMUNI Application</h1>
        <h2 id="white-text">Part 7 - Finish</h2><br>

        <div class="jumbotron">
            <h1>You made it!</h1><br>
            <p>Great job. Click submit below if you are finished.</p><br>
            <%= link_to("Submit Application", submit_path, method: :post, data: { confirm: "Are you sure you want to submit your application?" }, class: 'btn btn-primary') %>
        </div>
        <nav>
          <ul class="pagination pagination-lg pagination-centered">
            <li><%= link_to '<<', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '1'}) %></li>
            <li><%= link_to '1', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '1'}) %></li>
            <li><%= link_to '2', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '2'}) %></li>
            <li><%= link_to '3', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '3'}) %></li>
            <li><%= link_to '4', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '4'}) %></li>
            <li><%= link_to '5', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '5'}) %></li>
            <li><%= link_to '6', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '6'}) %></li>
	        <li class="active"><%= link_to '7', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '7'}) %></li>
            <li><%= link_to '>>', '#' %></li>
          </ul>
        </nav>
    </div>
</div>

app/views/apps/edit.html.erb
<% provide(:title, "YMUNI Application") %>

<div class="row" id="grad">
    <%= render 'shared/quick_links' %>

    <div class="col-md-6" > <!--col-md-offset-3">-->
        <h1 id="white-text">YMUNI Application</h1>
        <h2 id="white-text">Part 1 - General Information</h2><br>
    
        <div class="jumbotron">
            <%= form_for([@user, @app]) do |f| %>
                <%= hidden_field_tag 'page', params[:page] %>
                <%= render 'shared/app_error_messages' %>

                <%= f.label :first_name %><br>
                <%= f.text_field :first_name, class: 'form-control' %><br>

                <%= f.label :middle_name %><br>
                <%= f.text_field :middle_name, class: 'form-control' %><br>

                <%= f.label :last_name %><br>
                <%= f.text_field :last_name, class: 'form-control' %><br>

                <%= f.label :address %><br>
                <%= f.text_field :address, class: 'form-control' %><br>

                <%= f.label :city %><br>
                <%= f.text_field :city, class: 'form-control' %><br>

                <%= f.label :state %><br>
                <%= f.text_field :state, class: 'form-control' %><br>

                <%= f.label :zip_code %><br>
                <%= f.text_field :zip_code, class: 'form-control' %><br>

                <%= f.label :country %><br>
                <%= f.text_field :country, class: 'form-control' %><br>

                <%= f.label :date_of_birth %><br>
                <%= f.date_select :date_of_birth, :start_year => 1996, class: 'form-control' %><br>

                <%= f.label :ethnicity %><br>
                <%= f.text_field :ethnicity, class: 'form-control' %><br>

                <%= f.label :school_name %><br>
                <%= f.text_field :school_name, class: 'form-control' %><br>

                <%= f.label :school_address %><br>
                <%= f.text_field :school_address, class: 'form-control' %><br>

                <%= f.label :school_city %><br>
                <%= f.text_field :school_city, class: 'form-control' %><br>

                <%= f.label :school_state %><br>
                <%= f.text_field :school_state, class: 'form-control' %><br>

                <%= f.label :school_zip_code %><br>
                <%= f.text_field :school_zip_code, class: 'form-control' %><br>

                <%= f.label :school_country %><br>
                <%= f.text_field :school_country, class: 'form-control' %><br>

                <%= f.label :grade_level %><br>
                <%= f.select :grade_level, ['Sophomore', 'Junior', 'Senior'], {:selected => @app.grade_level}, class: 'form-control' %><br>

                <%= f.label :phone_number %>
                <%= f.text_field :phone_number, class: 'form-control' %><br>
               
                <%= f.submit "Save changes", class: 'btn btn-primary' %>
            <% end %>
        </div>

    <nav>
        <ul class="pagination pagination-lg pagination-centered">
        <li><%= link_to '<<', '#' %></li>
        <li class="active"><%= link_to '1', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '1'}) %> </li>
        <li><%= link_to '2', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '2'}) %></li>
        <li><%= link_to '3', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '3'}) %></li>
        <li><%= link_to '4', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '4'}) %></li>
        <li><%= link_to '5', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '5'}) %></li>
        <li><%= link_to '6', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '6'}) %></li>
        <li><%= link_to '7', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '7'}) %></li>
        <li><%= link_to '>>', edit_applicant_app_path(current_user, current_user.app, :params => {:page => '2'}) %></li>
        </ul>
    </nav>
  </div>
</div>

app/views/apps/show.html.erb
<% provide(:title, "YMUNI Application") %>

<div class="row" id="grad">
  <div class="col-md-10 col-md-offset-1">
  	<%= render 'shared/error_messages' %>

    <h1 id="white-text"><%= @app.first_name %>'s YMUNI Application</h1><br>

    <div class="jumbotron">
        <h2>Part 1 - General Information</h2><br>
	    <p>
			<strong>First name:</strong>
			<%= @app.first_name %>
		</p>
		<p>
			<strong>Middle name:</strong>
			<%= @app.middle_name %>
		</p>
		<p>
			<strong>Last name:</strong>
			<%= @app.last_name %>
		</p>
		<p>
			<strong>Address:</strong>
			<%= @app.address %>
		</p>
		<p>
			<strong>City:</strong>
			<%= @app.city %>
		</p>
		<p>
			<strong>State:</strong>
			<%= @app.state %>
		</p>
		<p>
			<strong>Zip Code:</strong>
			<%= @app.zip_code %>
		</p>
		<p>
			<strong>Country:</strong>
			<%= @app.country %>
		</p>
		<p>
			<strong>Date of Birth:</strong>
			<%= @app.date_of_birth %>
		</p>
		<p>
			<strong>Ethnicity:</strong>
			<%= @app.ethnicity %>
		</p>
		<p>
			<strong>School Name:</strong>
			<%= @app.school_name %>
		</p>
		<p>
			<strong>School Address:</strong>
			<%= @app.school_address %>
		</p>
		<p>
			<strong>School City:</strong>
			<%= @app.school_city %>
		</p>
		<p>
			<strong>School State:</strong>
			<%= @app.school_state %>
		</p>
		<p>
			<strong>School Zip Code:</strong>
			<%= @app.school_zip_code %>
		</p>
		<p>
			<strong>School Country:</strong>
			<%= @app.school_country %>
		</p>
		<p>
			<strong>Grade Level:</strong>
			<%= @app.grade_level %>
		</p>
	</div>

	<div class="jumbotron">
        <h2>Part 2 - Essays</h2><br>
	    <p>
			<strong>Personal Statement:</strong>
			<%= @app.personal_statement %>
		</p>
		<p>
			<strong>Supplemental Question 1:</strong>
			<%= @app.supplemental_question_1 %>
		</p>
		<p>
			<strong>Supplemental Question 2:</strong>
			<%= @app.supplemental_question_2 %>
		</p>
		<p>
			<strong>Supplemental Question 3:</strong>
			<%= @app.supplemental_question_3 %>
		</p>
		<p>
			<strong>Supplemental Question 4:</strong>
			<%= @app.supplemental_question_4 %>
		</p>
		<p>
			<strong>Supplemental Question 5:</strong>
			<%= @app.supplemental_question_5 %>
		</p>    
	</div>

	<div class="jumbotron">
        <h2>Part 3 - Letter of Recommendation</h2><br>
		
		<p>
			<% if File.exists?("#{@user.recommendation.path}") %>
				<%= link_to("Download letter of recommendation", recommendation_path) %>
			<% else %>
				<h3>No recommendation submitted!</h3>
			<% end %>
		</p>
	</div>

	<div class="jumbotron">
        <h2>Part 4 - Resume</h2><br>
		
		<p>
			<!--<%= "#{@user.resume.path}" %>-->
			<% if File.exists?("#{@user.resume.path}") %>
				<%= link_to("Download resume", resume_path) %>
			<% else %>
				<h3>No resume submitted!</h3>
			<% end %>
		</p>
	</div>

	<div class="jumbotron">
        <h2>Part 5 - GPA and Scores</h2><br>
	    <p>
			<strong>GPA:</strong>
			<%= @app.gpa %>
		</p>
		<p>
			<strong>SAT Score:</strong>
			<%= @app.sat_score %>
		</p>
		<p>
			<strong>ACT Score:</strong>
			<%= @app.act_score %>
		</p>
		<p>
			<strong>TOEFL Score:</strong>
			<%= @app.toefl_score %>
		</p>
	</div>

	<div class="jumbotron">
        <h2>Part 6 - Additional Comments</h2><br>
	    <p>
			<%= @app.additional_comments %>
		</p>
	</div>
  </div>
</div>

app/views/apps/status.html.erb
<% provide(:title, "YMUNI Application") %>

<div class="row" id="grad">
    <div class="col-md-8 col-md-offset-2">
        <h1 id="white-text">Application Status</h1>

        <div class="jumbotron">
            <h2>Your application has been submitted and is now under review.</h2><br><br>

            <p>After all applications have been reviewed, your decision will be posted here.</p>

            <p>You will get an email notification when this happens.</p>

            <p>Thanks!</p>
        </div>
  </div>
</div>